### ISSUE TITLE
Random JSF salt for oxAuth

### ISSUE THREAD

**Issue by iromli** [GluuFederation/gluu-flask#54]
As seen in https://github.com/GluuFederation/community-edition-setup/commit/9d2f97d4f7448752cca6c04242aa81fd1029a262

**Comment by iromli** [comment]
Login via oxAuth worked, however when starting Tomcat, i got error message `Failed to determine supportedLDAPVersion` in log:

```
2015-12-13 16:40:22,506 INFO  [org.xdi.oxauth.model.util.JwtUtil] Adding Bouncy Castle Provider
2015-12-13 16:40:22,925 ERROR [org.gluu.site.ldap.LDAPConnectionProvider] Failed to determine supportedLDAPVersion
LDAPSearchException(resultCode=53 (unwilling to perform), numEntries=0, numReferences=0, errorMessage='Rejecting the requested operation  because the connection has not been authenticated')
	at com.unboundid.ldap.sdk.LDAPConnection.search(LDAPConnection.java:3112)
	at com.unboundid.ldap.sdk.LDAPConnection.getEntry(LDAPConnection.java:1422)
	at com.unboundid.ldap.sdk.RootDSE.getRootDSE(RootDSE.java:264)
	at com.unboundid.ldap.sdk.LDAPConnection.getRootDSE(LDAPConnection.java:1320)
	at com.unboundid.ldap.sdk.AbstractConnectionPool.getRootDSE(AbstractConnectionPool.java:438)
	at org.gluu.site.ldap.LDAPConnectionProvider.determineSupportedLdapVersion(LDAPConnectionProvider.java:140)
	at org.gluu.site.ldap.LDAPConnectionProvider.init(LDAPConnectionProvider.java:129)
	at org.gluu.site.ldap.LDAPConnectionProvider.<init>(LDAPConnectionProvider.java:59)
	at org.xdi.service.ldap.LdapConnectionService.<init>(LdapConnectionService.java:21)
	at org.xdi.oxauth.service.AppInitializer.createConnectionProvider(AppInitializer.java:335)
	at org.xdi.oxauth.service.AppInitializer.createBindConnectionProvider(AppInitializer.java:341)
	at org.xdi.oxauth.service.AppInitializer.createConnectionProvider(AppInitializer.java:273)
	at org.xdi.oxauth.service.AppInitializer.createApplicationComponents(AppInitializer.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.seam.util.Reflections.invoke(Reflections.java:22)
	at org.jboss.seam.intercept.RootInvocationContext.proceed(RootInvocationContext.java:32)
	at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:56)
	at org.jboss.seam.transaction.RollbackInterceptor.aroundInvoke(RollbackInterceptor.java:28)
	at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
	at org.jboss.seam.core.BijectionInterceptor.aroundInvoke(BijectionInterceptor.java:77)
	at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
	at org.jboss.seam.core.MethodContextInterceptor.aroundInvoke(MethodContextInterceptor.java:44)
	at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
	at org.jboss.seam.async.AsynchronousInterceptor.aroundInvoke(AsynchronousInterceptor.java:52)
	at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
	at org.jboss.seam.intercept.RootInterceptor.invoke(RootInterceptor.java:107)
	at org.jboss.seam.intercept.JavaBeanInterceptor.interceptInvocation(JavaBeanInterceptor.java:185)
	at org.jboss.seam.intercept.JavaBeanInterceptor.invoke(JavaBeanInterceptor.java:103)
	at org.xdi.oxauth.service.AppInitializer_$$_javassist_seam_1.createApplicationComponents(AppInitializer_$$_javassist_seam_1.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.seam.util.Reflections.invoke(Reflections.java:22)
	at org.jboss.seam.util.Reflections.invokeAndWrap(Reflections.java:144)
	at org.jboss.seam.Component.callComponentMethod(Component.java:2275)
	at org.jboss.seam.Component.callCreateMethod(Component.java:2198)
	at org.jboss.seam.Component.newInstance(Component.java:2158)
	at org.jboss.seam.contexts.Contexts.startup(Contexts.java:304)
	at org.jboss.seam.contexts.Contexts.startup(Contexts.java:278)
	at org.jboss.seam.contexts.ServletLifecycle.endInitialization(ServletLifecycle.java:143)
	at org.jboss.seam.init.Initialization.init(Initialization.java:744)
	at org.jboss.seam.servlet.SeamListener.contextInitialized(SeamListener.java:36)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5003)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5517)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:677)
	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1942)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
2015-12-13 16:40:22,928 INFO  [org.xdi.oxauth.model.config.ConfigurationFactory] Loading configuration from LDAP...
2015-12-13 16:40:23,059 DEBUG [org.xdi.oxauth.service.AppInitializer] Created ldapEntryManager: org.gluu.site.ldap.persistence.LdapEntryManager@9f1f3ee
2015-12-13 16:40:23,297 INFO  [org.xdi.oxauth.model.config.ConfigurationFactory] Configuration loaded successfully.
2015-12-13 16:40:23,619 ERROR [org.gluu.site.ldap.LDAPConnectionProvider] Failed to determine supportedLDAPVersion
LDAPSearchException(resultCode=53 (unwilling to perform), numEntries=0, numReferences=0, errorMessage='Rejecting the requested operation  because the connection has not been authenticated')
	at com.unboundid.ldap.sdk.LDAPConnection.search(LDAPConnection.java:3112)
	at com.unboundid.ldap.sdk.LDAPConnection.getEntry(LDAPConnection.java:1422)
	at com.unboundid.ldap.sdk.RootDSE.getRootDSE(RootDSE.java:264)
	at com.unboundid.ldap.sdk.LDAPConnection.getRootDSE(LDAPConnection.java:1320)
	at com.unboundid.ldap.sdk.AbstractConnectionPool.getRootDSE(AbstractConnectionPool.java:438)
	at org.gluu.site.ldap.LDAPConnectionProvider.determineSupportedLdapVersion(LDAPConnectionProvider.java:140)
	at org.gluu.site.ldap.LDAPConnectionProvider.init(LDAPConnectionProvider.java:129)
	at org.gluu.site.ldap.LDAPConnectionProvider.<init>(LDAPConnectionProvider.java:59)
	at org.xdi.service.ldap.LdapConnectionService.<init>(LdapConnectionService.java:21)
	at org.xdi.oxauth.service.AppInitializer.createConnectionProvider(AppInitializer.java:335)
	at org.xdi.oxauth.service.AppInitializer.createBindConnectionProvider(AppInitializer.java:341)
	at org.xdi.oxauth.service.AppInitializer.createAuthConnectionProviders(AppInitializer.java:300)
	at org.xdi.oxauth.service.AppInitializer.createAuthConnectionProviders(AppInitializer.java:282)
	at org.xdi.oxauth.service.AppInitializer.createApplicationComponents(AppInitializer.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.seam.util.Reflections.invoke(Reflections.java:22)
	at org.jboss.seam.intercept.RootInvocationContext.proceed(RootInvocationContext.java:32)
	at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:56)
	at org.jboss.seam.transaction.RollbackInterceptor.aroundInvoke(RollbackInterceptor.java:28)
	at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
	at org.jboss.seam.core.BijectionInterceptor.aroundInvoke(BijectionInterceptor.java:77)
	at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
	at org.jboss.seam.core.MethodContextInterceptor.aroundInvoke(MethodContextInterceptor.java:44)
	at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
	at org.jboss.seam.async.AsynchronousInterceptor.aroundInvoke(AsynchronousInterceptor.java:52)
	at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
	at org.jboss.seam.intercept.RootInterceptor.invoke(RootInterceptor.java:107)
	at org.jboss.seam.intercept.JavaBeanInterceptor.interceptInvocation(JavaBeanInterceptor.java:185)
	at org.jboss.seam.intercept.JavaBeanInterceptor.invoke(JavaBeanInterceptor.java:103)
	at org.xdi.oxauth.service.AppInitializer_$$_javassist_seam_1.createApplicationComponents(AppInitializer_$$_javassist_seam_1.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.seam.util.Reflections.invoke(Reflections.java:22)
	at org.jboss.seam.util.Reflections.invokeAndWrap(Reflections.java:144)
	at org.jboss.seam.Component.callComponentMethod(Component.java:2275)
	at org.jboss.seam.Component.callCreateMethod(Component.java:2198)
	at org.jboss.seam.Component.newInstance(Component.java:2158)
	at org.jboss.seam.contexts.Contexts.startup(Contexts.java:304)
	at org.jboss.seam.contexts.Contexts.startup(Contexts.java:278)
	at org.jboss.seam.contexts.ServletLifecycle.endInitialization(ServletLifecycle.java:143)
	at org.jboss.seam.init.Initialization.init(Initialization.java:744)
	at org.jboss.seam.servlet.SeamListener.contextInitialized(SeamListener.java:36)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5003)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5517)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:677)
	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1942)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
2015-12-13 16:40:23,722 INFO  [org.xdi.oxauth.model.common.AuthorizationGrantList] Created LDAP authorization grant list
2015-12-13 16:40:23,743 INFO  [org.jboss.seam.resteasy.ResteasyBootstrap] bootstrapping JAX-RS application
2015-12-13 16:40:23,780 INFO  [org.jboss.seam.resteasy.ResteasyBootstrap] registering built-in RESTEasy providers
2015-12-13 16:40:24,066 INFO  [org.xdi.oxauth.service.uma.RPTManager] Created LDAP UMA RPT manager
2015-12-13 16:40:24,070 INFO  [org.xdi.oxauth.service.uma.ResourceSetPermissionManager] Created LDAP UMA resource set manager
2015-12-13 16:40:24,076 DEBUG [org.xdi.oxauth.service.CleanerTimer] Initializing CleanerTimer
2015-12-13 16:40:24,081 DEBUG [org.xdi.oxauth.service.KeyGeneratorTimer] Initializing KeyGeneratorTimer
```

I've tried to import cert from LDAP server and restarted oxAuth, but the error is still there.
@yurem is there something missing in the templates or config?

**Comment by yurem** [comment]
It's not cert issue. JSF salt can't cause this issue too. Did you disable anonymous bind? Can you open oxAuth issue with this stack trace or reference to this issue? I will take a look on it.

**Comment by iromli** [comment]
> It's not cert issue. JSF salt can't cause this issue too.

Noted.

> Can you open oxAuth issue with this stack trace or reference to this issue?

Yes, I can do that. I will try to reproduce the issue again.
Thanks.
